server:
  port: 8762

spring:
  application:
    name: service-sayhi

eureka:
#  instance:
#    lease-expiration-duration-in-seconds: 30 # 续约更新时间间隔（默认30秒）
#    lease-renewal-interval-in-seconds:  90  # 续约到期时间（默认90秒）
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

